#!/bin/bash
# Growth-OS Folder Structure Generator
# Run: chmod +x create_growth_os.sh && ./create_growth_os.sh

ROOT="Growth-OS"
COUNT=0

mk() {
    mkdir -p "$1"
    touch "$1/.gitkeep"
    echo "  ✓ $1"
    ((COUNT++))
}

echo ""
echo "🚀 Growth-OS Folder Generator"
echo "📍 Location: $(pwd)"
echo "--------------------------------------------------"

# .claude
mk "$ROOT/.claude/System Prompts/Growth Strategy Prompts"
mk "$ROOT/.claude/System Prompts/Lead Gen Prompts"
mk "$ROOT/.claude/System Prompts/Copywriting Prompts"
mk "$ROOT/.claude/System Prompts/Outreach Prompts"
mk "$ROOT/.claude/System Prompts/Analytics Prompts"
mk "$ROOT/.claude/Agents/Lead Research Agent"
mk "$ROOT/.claude/Agents/Outreach Agent"
mk "$ROOT/.claude/Agents/Content Agent"
mk "$ROOT/.claude/Agents/SEO Agent"
mk "$ROOT/.claude/Agents/Analytics Agent"
mk "$ROOT/.claude/Workflows/Lead Gen Workflow"
mk "$ROOT/.claude/Workflows/Campaign Workflow"
mk "$ROOT/.claude/Workflows/BD Workflow"
mk "$ROOT/.claude/Workflows/Growth Experiment Workflow"
mk "$ROOT/.claude/Memory/Brand Voice"
mk "$ROOT/.claude/Memory/ICP Profiles"
mk "$ROOT/.claude/Memory/Competitor Intel"
mk "$ROOT/.claude/Memory/Market Context"
mk "$ROOT/.claude/MCP Configs/CRM Connections"
mk "$ROOT/.claude/MCP Configs/Email Platform Configs"
mk "$ROOT/.claude/MCP Configs/Analytics Connections"

# Business Growth
mk "$ROOT/Business Growth/Growth Strategy/Growth Vision"
mk "$ROOT/Business Growth/Growth Strategy/Growth Framework"
mk "$ROOT/Business Growth/Growth Strategy/Ansoff Matrix"
mk "$ROOT/Business Growth/Growth Strategy/Market Penetration"
mk "$ROOT/Business Growth/Growth Strategy/Market Development"
mk "$ROOT/Business Growth/Growth Strategy/Product Development"
mk "$ROOT/Business Growth/Growth Strategy/Diversification"
mk "$ROOT/Business Growth/Revenue Growth/Revenue Streams"
mk "$ROOT/Business Growth/Revenue Growth/Upsell Strategy"
mk "$ROOT/Business Growth/Revenue Growth/Cross Sell Strategy"
mk "$ROOT/Business Growth/Revenue Growth/Expansion Revenue"
mk "$ROOT/Business Growth/Revenue Growth/Pricing Optimization"
mk "$ROOT/Business Growth/Revenue Growth/Revenue Forecasts"
mk "$ROOT/Business Growth/Customer Growth/Acquisition Strategy"
mk "$ROOT/Business Growth/Customer Growth/Activation Plans"
mk "$ROOT/Business Growth/Customer Growth/Retention Programs"
mk "$ROOT/Business Growth/Customer Growth/Referral Programs"
mk "$ROOT/Business Growth/Customer Growth/Win Back Campaigns"
mk "$ROOT/Business Growth/Market Expansion/New Market Research"
mk "$ROOT/Business Growth/Market Expansion/Geographic Expansion"
mk "$ROOT/Business Growth/Market Expansion/Vertical Expansion"
mk "$ROOT/Business Growth/Market Expansion/Entry Strategy"
mk "$ROOT/Business Growth/Market Expansion/Localization Plans"
mk "$ROOT/Business Growth/Growth OKRs/Company OKRs"
mk "$ROOT/Business Growth/Growth OKRs/Growth KPIs"
mk "$ROOT/Business Growth/Growth OKRs/North Star Metric"
mk "$ROOT/Business Growth/Growth OKRs/Leading Indicators"
mk "$ROOT/Business Growth/Growth OKRs/Lagging Indicators"
mk "$ROOT/Business Growth/Competitive Positioning/Competitor Analysis"
mk "$ROOT/Business Growth/Competitive Positioning/Differentiation Strategy"
mk "$ROOT/Business Growth/Competitive Positioning/Moat Building"
mk "$ROOT/Business Growth/Competitive Positioning/Positioning Maps"
mk "$ROOT/Business Growth/Competitive Positioning/Blue Ocean Strategy"
mk "$ROOT/Business Growth/Funding & Investment/Pitch Decks"
mk "$ROOT/Business Growth/Funding & Investment/Investor Pipeline"
mk "$ROOT/Business Growth/Funding & Investment/Financial Projections"
mk "$ROOT/Business Growth/Funding & Investment/Due Diligence Prep"
mk "$ROOT/Business Growth/Funding & Investment/Cap Table"
mk "$ROOT/Business Growth/AI Workflows/Growth Strategy Builder"
mk "$ROOT/Business Growth/AI Workflows/Revenue Model Analyzer"
mk "$ROOT/Business Growth/AI Workflows/Expansion Planner"

# Lead Generation
mk "$ROOT/Lead Generation/ICP & Personas/Ideal Customer Profiles"
mk "$ROOT/Lead Generation/ICP & Personas/Buyer Personas"
mk "$ROOT/Lead Generation/ICP & Personas/Pain Point Library"
mk "$ROOT/Lead Generation/ICP & Personas/Job Title Targeting"
mk "$ROOT/Lead Generation/ICP & Personas/Persona Research"
mk "$ROOT/Lead Generation/Inbound Lead Gen/SEO Strategy"
mk "$ROOT/Lead Generation/Inbound Lead Gen/Content Marketing"
mk "$ROOT/Lead Generation/Inbound Lead Gen/Lead Magnets"
mk "$ROOT/Lead Generation/Inbound Lead Gen/Gated Content"
mk "$ROOT/Lead Generation/Inbound Lead Gen/Webinars"
mk "$ROOT/Lead Generation/Inbound Lead Gen/Free Tools"
mk "$ROOT/Lead Generation/Outbound Lead Gen/Prospect Lists"
mk "$ROOT/Lead Generation/Outbound Lead Gen/Cold Email"
mk "$ROOT/Lead Generation/Outbound Lead Gen/LinkedIn Outreach"
mk "$ROOT/Lead Generation/Outbound Lead Gen/Cold Calling"
mk "$ROOT/Lead Generation/Outbound Lead Gen/Direct Mail"
mk "$ROOT/Lead Generation/Outbound Lead Gen/Account Based Outreach"
mk "$ROOT/Lead Generation/Lead Magnets/eBooks & Guides"
mk "$ROOT/Lead Generation/Lead Magnets/Templates"
mk "$ROOT/Lead Generation/Lead Magnets/Checklists"
mk "$ROOT/Lead Generation/Lead Magnets/Free Calculators"
mk "$ROOT/Lead Generation/Lead Magnets/Mini Courses"
mk "$ROOT/Lead Generation/Lead Magnets/Research Reports"
mk "$ROOT/Lead Generation/Lead Scoring/Scoring Models"
mk "$ROOT/Lead Generation/Lead Scoring/MQL Definition"
mk "$ROOT/Lead Generation/Lead Scoring/SQL Definition"
mk "$ROOT/Lead Generation/Lead Scoring/PQL Definition"
mk "$ROOT/Lead Generation/Lead Scoring/Score Thresholds"
mk "$ROOT/Lead Generation/Lead Capture/Landing Pages"
mk "$ROOT/Lead Generation/Lead Capture/Forms & CTAs"
mk "$ROOT/Lead Generation/Lead Capture/Pop Ups"
mk "$ROOT/Lead Generation/Lead Capture/Chatbots"
mk "$ROOT/Lead Generation/Lead Capture/Exit Intent"
mk "$ROOT/Lead Generation/Lead Nurturing/Drip Sequences"
mk "$ROOT/Lead Generation/Lead Nurturing/Nurture Tracks"
mk "$ROOT/Lead Generation/Lead Nurturing/Re Engagement"
mk "$ROOT/Lead Generation/Lead Nurturing/Lead Warming"
mk "$ROOT/Lead Generation/Lead Nurturing/Sales Handoff"
mk "$ROOT/Lead Generation/Lead Database/Raw Leads"
mk "$ROOT/Lead Generation/Lead Database/Qualified Leads"
mk "$ROOT/Lead Generation/Lead Database/Disqualified Leads"
mk "$ROOT/Lead Generation/Lead Database/Recycled Leads"
mk "$ROOT/Lead Generation/Lead Database/Lead Sources"
mk "$ROOT/Lead Generation/Tools & Automation/Apollo"
mk "$ROOT/Lead Generation/Tools & Automation/Hunter.io"
mk "$ROOT/Lead Generation/Tools & Automation/ZoomInfo"
mk "$ROOT/Lead Generation/Tools & Automation/Clay"
mk "$ROOT/Lead Generation/Tools & Automation/Phantombuster"
mk "$ROOT/Lead Generation/Tools & Automation/Lemlist"
mk "$ROOT/Lead Generation/AI Workflows/ICP Builder"
mk "$ROOT/Lead Generation/AI Workflows/Lead Enricher"
mk "$ROOT/Lead Generation/AI Workflows/Outreach Personalizer"

# Marketing Strategies
mk "$ROOT/Marketing Strategies/Brand Strategy/Brand Positioning"
mk "$ROOT/Marketing Strategies/Brand Strategy/Brand Architecture"
mk "$ROOT/Marketing Strategies/Brand Strategy/Brand Voice & Tone"
mk "$ROOT/Marketing Strategies/Brand Strategy/Messaging Framework"
mk "$ROOT/Marketing Strategies/Brand Strategy/Taglines"
mk "$ROOT/Marketing Strategies/Brand Strategy/Story Brand"
mk "$ROOT/Marketing Strategies/Content Marketing/Content Strategy"
mk "$ROOT/Marketing Strategies/Content Marketing/Content Calendar"
mk "$ROOT/Marketing Strategies/Content Marketing/Blog"
mk "$ROOT/Marketing Strategies/Content Marketing/Video"
mk "$ROOT/Marketing Strategies/Content Marketing/Podcast"
mk "$ROOT/Marketing Strategies/Content Marketing/Newsletters"
mk "$ROOT/Marketing Strategies/Content Marketing/Long Form Content"
mk "$ROOT/Marketing Strategies/Social Media/Platform Strategy"
mk "$ROOT/Marketing Strategies/Social Media/LinkedIn"
mk "$ROOT/Marketing Strategies/Social Media/Twitter X"
mk "$ROOT/Marketing Strategies/Social Media/Instagram"
mk "$ROOT/Marketing Strategies/Social Media/TikTok"
mk "$ROOT/Marketing Strategies/Social Media/YouTube"
mk "$ROOT/Marketing Strategies/Social Media/Facebook"
mk "$ROOT/Marketing Strategies/Social Media/Scheduling & Automation"
mk "$ROOT/Marketing Strategies/Email Marketing/List Building"
mk "$ROOT/Marketing Strategies/Email Marketing/Segmentation"
mk "$ROOT/Marketing Strategies/Email Marketing/Campaigns"
mk "$ROOT/Marketing Strategies/Email Marketing/Automation Flows"
mk "$ROOT/Marketing Strategies/Email Marketing/A-B Testing"
mk "$ROOT/Marketing Strategies/Email Marketing/Deliverability"
mk "$ROOT/Marketing Strategies/SEO/Keyword Strategy"
mk "$ROOT/Marketing Strategies/SEO/On Page SEO"
mk "$ROOT/Marketing Strategies/SEO/Technical SEO"
mk "$ROOT/Marketing Strategies/SEO/Link Building"
mk "$ROOT/Marketing Strategies/SEO/Local SEO"
mk "$ROOT/Marketing Strategies/SEO/SEO Reporting"
mk "$ROOT/Marketing Strategies/Paid Advertising/Google Ads"
mk "$ROOT/Marketing Strategies/Paid Advertising/Meta Ads"
mk "$ROOT/Marketing Strategies/Paid Advertising/LinkedIn Ads"
mk "$ROOT/Marketing Strategies/Paid Advertising/YouTube Ads"
mk "$ROOT/Marketing Strategies/Paid Advertising/Programmatic"
mk "$ROOT/Marketing Strategies/Paid Advertising/Retargeting"
mk "$ROOT/Marketing Strategies/Paid Advertising/Ad Creative Library"
mk "$ROOT/Marketing Strategies/Influencer Marketing/Influencer Database"
mk "$ROOT/Marketing Strategies/Influencer Marketing/Outreach Templates"
mk "$ROOT/Marketing Strategies/Influencer Marketing/Campaign Briefs"
mk "$ROOT/Marketing Strategies/Influencer Marketing/Contracts"
mk "$ROOT/Marketing Strategies/Influencer Marketing/Performance Tracking"
mk "$ROOT/Marketing Strategies/Event Marketing/Webinars"
mk "$ROOT/Marketing Strategies/Event Marketing/Conferences"
mk "$ROOT/Marketing Strategies/Event Marketing/Virtual Events"
mk "$ROOT/Marketing Strategies/Event Marketing/Sponsorships"
mk "$ROOT/Marketing Strategies/Event Marketing/Event Recaps"
mk "$ROOT/Marketing Strategies/Marketing Analytics/Campaign Reports"
mk "$ROOT/Marketing Strategies/Marketing Analytics/Attribution Models"
mk "$ROOT/Marketing Strategies/Marketing Analytics/Channel ROI"
mk "$ROOT/Marketing Strategies/Marketing Analytics/Marketing Dashboards"
mk "$ROOT/Marketing Strategies/Marketing Analytics/Budget Allocation"
mk "$ROOT/Marketing Strategies/Go To Market/GTM Playbooks"
mk "$ROOT/Marketing Strategies/Go To Market/Launch Plans"
mk "$ROOT/Marketing Strategies/Go To Market/Positioning"
mk "$ROOT/Marketing Strategies/Go To Market/Pricing Strategy"
mk "$ROOT/Marketing Strategies/Go To Market/Sales Enablement"
mk "$ROOT/Marketing Strategies/AI Workflows/Campaign Builder"
mk "$ROOT/Marketing Strategies/AI Workflows/Copy Generator"
mk "$ROOT/Marketing Strategies/AI Workflows/Strategy Analyzer"

# Growth Hacking
mk "$ROOT/Growth Hacking/Experimentation/Experiment Backlog"
mk "$ROOT/Growth Hacking/Experimentation/Running Experiments"
mk "$ROOT/Growth Hacking/Experimentation/Completed Experiments"
mk "$ROOT/Growth Hacking/Experimentation/Experiment Results"
mk "$ROOT/Growth Hacking/Experimentation/Learning Library"
mk "$ROOT/Growth Hacking/A-B Testing/Landing Page Tests"
mk "$ROOT/Growth Hacking/A-B Testing/Pricing Tests"
mk "$ROOT/Growth Hacking/A-B Testing/Onboarding Tests"
mk "$ROOT/Growth Hacking/A-B Testing/Email Tests"
mk "$ROOT/Growth Hacking/A-B Testing/CTA Tests"
mk "$ROOT/Growth Hacking/Viral Loops/Referral Mechanics"
mk "$ROOT/Growth Hacking/Viral Loops/Share Triggers"
mk "$ROOT/Growth Hacking/Viral Loops/Virality Coefficient"
mk "$ROOT/Growth Hacking/Viral Loops/Invite Flows"
mk "$ROOT/Growth Hacking/Viral Loops/Loop Analysis"
mk "$ROOT/Growth Hacking/Product Led Growth/PLG Strategy"
mk "$ROOT/Growth Hacking/Product Led Growth/Freemium Model"
mk "$ROOT/Growth Hacking/Product Led Growth/Free Trial Design"
mk "$ROOT/Growth Hacking/Product Led Growth/Aha Moment Map"
mk "$ROOT/Growth Hacking/Product Led Growth/Activation Funnel"
mk "$ROOT/Growth Hacking/Product Led Growth/PQL Framework"
mk "$ROOT/Growth Hacking/Product Led Growth/Expansion Triggers"
mk "$ROOT/Growth Hacking/Conversion Rate Optimization/CRO Audits"
mk "$ROOT/Growth Hacking/Conversion Rate Optimization/Heatmap Analysis"
mk "$ROOT/Growth Hacking/Conversion Rate Optimization/Session Recordings"
mk "$ROOT/Growth Hacking/Conversion Rate Optimization/UX Friction Points"
mk "$ROOT/Growth Hacking/Conversion Rate Optimization/Form Optimization"
mk "$ROOT/Growth Hacking/Conversion Rate Optimization/Checkout Optimization"
mk "$ROOT/Growth Hacking/Acquisition Hacks/Community Infiltration"
mk "$ROOT/Growth Hacking/Acquisition Hacks/Platform Arbitrage"
mk "$ROOT/Growth Hacking/Acquisition Hacks/SEO Hacks"
mk "$ROOT/Growth Hacking/Acquisition Hacks/PR Stunts"
mk "$ROOT/Growth Hacking/Acquisition Hacks/Partnership Hacks"
mk "$ROOT/Growth Hacking/Retention Hacks/Habit Forming Loops"
mk "$ROOT/Growth Hacking/Retention Hacks/Gamification"
mk "$ROOT/Growth Hacking/Retention Hacks/Push Notifications"
mk "$ROOT/Growth Hacking/Retention Hacks/Re Engagement Flows"
mk "$ROOT/Growth Hacking/Retention Hacks/Power User Programs"
mk "$ROOT/Growth Hacking/Monetization Hacks/Pricing Psychology"
mk "$ROOT/Growth Hacking/Monetization Hacks/Urgency & Scarcity"
mk "$ROOT/Growth Hacking/Monetization Hacks/Bundle Strategies"
mk "$ROOT/Growth Hacking/Monetization Hacks/Downsell Flows"
mk "$ROOT/Growth Hacking/Monetization Hacks/LTV Maximization"
mk "$ROOT/Growth Hacking/Data Driven Growth/Growth Models"
mk "$ROOT/Growth Hacking/Data Driven Growth/Cohort Analysis"
mk "$ROOT/Growth Hacking/Data Driven Growth/Funnel Metrics"
mk "$ROOT/Growth Hacking/Data Driven Growth/Growth Accounting"
mk "$ROOT/Growth Hacking/Data Driven Growth/Predictive Models"
mk "$ROOT/Growth Hacking/Tools Stack/Analytics Tools"
mk "$ROOT/Growth Hacking/Tools Stack/Testing Tools"
mk "$ROOT/Growth Hacking/Tools Stack/Automation Tools"
mk "$ROOT/Growth Hacking/Tools Stack/Tracking Setup"
mk "$ROOT/Growth Hacking/AI Workflows/Experiment Designer"
mk "$ROOT/Growth Hacking/AI Workflows/Growth Lever Finder"
mk "$ROOT/Growth Hacking/AI Workflows/CRO Advisor"

# Business Development
mk "$ROOT/Business Development/BD Strategy/BD Vision"
mk "$ROOT/Business Development/BD Strategy/Target Markets"
mk "$ROOT/Business Development/BD Strategy/Revenue Targets"
mk "$ROOT/Business Development/BD Strategy/BD Playbook"
mk "$ROOT/Business Development/BD Strategy/Quarterly Plans"
mk "$ROOT/Business Development/Prospect Research/Target Account Lists"
mk "$ROOT/Business Development/Prospect Research/Account Intelligence"
mk "$ROOT/Business Development/Prospect Research/Decision Maker Maps"
mk "$ROOT/Business Development/Prospect Research/Buying Signals"
mk "$ROOT/Business Development/Prospect Research/Intent Data"
mk "$ROOT/Business Development/Outreach/Cold Email Sequences"
mk "$ROOT/Business Development/Outreach/LinkedIn Sequences"
mk "$ROOT/Business Development/Outreach/Call Scripts"
mk "$ROOT/Business Development/Outreach/Video Outreach"
mk "$ROOT/Business Development/Outreach/Multi Touch Sequences"
mk "$ROOT/Business Development/Outreach/Follow Up Templates"
mk "$ROOT/Business Development/Pipeline Management/Lead Stage"
mk "$ROOT/Business Development/Pipeline Management/Discovery Stage"
mk "$ROOT/Business Development/Pipeline Management/Proposal Stage"
mk "$ROOT/Business Development/Pipeline Management/Negotiation Stage"
mk "$ROOT/Business Development/Pipeline Management/Closed Won"
mk "$ROOT/Business Development/Pipeline Management/Closed Lost"
mk "$ROOT/Business Development/Proposals & Pitches/Proposal Templates"
mk "$ROOT/Business Development/Proposals & Pitches/Pitch Decks"
mk "$ROOT/Business Development/Proposals & Pitches/Case Studies"
mk "$ROOT/Business Development/Proposals & Pitches/Sent Proposals"
mk "$ROOT/Business Development/Proposals & Pitches/Won Proposals"
mk "$ROOT/Business Development/Partnerships/Strategic Partners"
mk "$ROOT/Business Development/Partnerships/Channel Partners"
mk "$ROOT/Business Development/Partnerships/Tech Partners"
mk "$ROOT/Business Development/Partnerships/Referral Partners"
mk "$ROOT/Business Development/Partnerships/Partner Agreements"
mk "$ROOT/Business Development/Partnerships/JV Opportunities"
mk "$ROOT/Business Development/Alliances/Co Marketing"
mk "$ROOT/Business Development/Alliances/Co Selling"
mk "$ROOT/Business Development/Alliances/White Label"
mk "$ROOT/Business Development/Alliances/Reseller Agreements"
mk "$ROOT/Business Development/Alliances/OEM Deals"
mk "$ROOT/Business Development/BD Analytics/Pipeline Reports"
mk "$ROOT/Business Development/BD Analytics/Win Loss Analysis"
mk "$ROOT/Business Development/BD Analytics/Activity Metrics"
mk "$ROOT/Business Development/BD Analytics/Revenue Attribution"
mk "$ROOT/Business Development/AI Workflows/Prospect Researcher"
mk "$ROOT/Business Development/AI Workflows/Proposal Builder"
mk "$ROOT/Business Development/AI Workflows/Deal Coach"

# Sales Funnel
mk "$ROOT/Sales Funnel/Top of Funnel/Awareness Campaigns"
mk "$ROOT/Sales Funnel/Top of Funnel/Brand Content"
mk "$ROOT/Sales Funnel/Top of Funnel/Thought Leadership"
mk "$ROOT/Sales Funnel/Top of Funnel/PR & Media"
mk "$ROOT/Sales Funnel/Top of Funnel/Paid Awareness"
mk "$ROOT/Sales Funnel/Middle of Funnel/Consideration Content"
mk "$ROOT/Sales Funnel/Middle of Funnel/Comparison Pages"
mk "$ROOT/Sales Funnel/Middle of Funnel/Case Studies"
mk "$ROOT/Sales Funnel/Middle of Funnel/Webinars"
mk "$ROOT/Sales Funnel/Middle of Funnel/Demo Offers"
mk "$ROOT/Sales Funnel/Bottom of Funnel/Sales Pages"
mk "$ROOT/Sales Funnel/Bottom of Funnel/Pricing Pages"
mk "$ROOT/Sales Funnel/Bottom of Funnel/Trial Offers"
mk "$ROOT/Sales Funnel/Bottom of Funnel/Objection Handling"
mk "$ROOT/Sales Funnel/Bottom of Funnel/Close Scripts"
mk "$ROOT/Sales Funnel/Funnel Optimization/Conversion Rates"
mk "$ROOT/Sales Funnel/Funnel Optimization/Drop Off Points"
mk "$ROOT/Sales Funnel/Funnel Optimization/Funnel Tests"
mk "$ROOT/Sales Funnel/Funnel Optimization/Optimization Roadmap"
mk "$ROOT/Sales Funnel/Post Purchase/Onboarding Flows"
mk "$ROOT/Sales Funnel/Post Purchase/Upsell Sequences"
mk "$ROOT/Sales Funnel/Post Purchase/Loyalty Programs"
mk "$ROOT/Sales Funnel/Post Purchase/Referral Asks"
mk "$ROOT/Sales Funnel/Post Purchase/Advocacy Programs"
mk "$ROOT/Sales Funnel/AI Workflows/Funnel Analyzer"
mk "$ROOT/Sales Funnel/AI Workflows/Drop Off Diagnoser"
mk "$ROOT/Sales Funnel/AI Workflows/Conversion Optimizer"

# Customer Acquisition
mk "$ROOT/Customer Acquisition/Acquisition Channels/Organic Search"
mk "$ROOT/Customer Acquisition/Acquisition Channels/Paid Search"
mk "$ROOT/Customer Acquisition/Acquisition Channels/Social Organic"
mk "$ROOT/Customer Acquisition/Acquisition Channels/Paid Social"
mk "$ROOT/Customer Acquisition/Acquisition Channels/Email"
mk "$ROOT/Customer Acquisition/Acquisition Channels/Referral"
mk "$ROOT/Customer Acquisition/Acquisition Channels/Direct"
mk "$ROOT/Customer Acquisition/Acquisition Channels/Partnerships"
mk "$ROOT/Customer Acquisition/CAC Management/CAC by Channel"
mk "$ROOT/Customer Acquisition/CAC Management/Blended CAC"
mk "$ROOT/Customer Acquisition/CAC Management/CAC Payback Period"
mk "$ROOT/Customer Acquisition/CAC Management/CAC Benchmarks"
mk "$ROOT/Customer Acquisition/CAC Management/CAC Reduction Plans"
mk "$ROOT/Customer Acquisition/Paid Acquisition/Google Ads"
mk "$ROOT/Customer Acquisition/Paid Acquisition/Meta Ads"
mk "$ROOT/Customer Acquisition/Paid Acquisition/LinkedIn Ads"
mk "$ROOT/Customer Acquisition/Paid Acquisition/Native Ads"
mk "$ROOT/Customer Acquisition/Paid Acquisition/Affiliate Programs"
mk "$ROOT/Customer Acquisition/Paid Acquisition/Ad Spend Tracker"
mk "$ROOT/Customer Acquisition/Organic Acquisition/SEO"
mk "$ROOT/Customer Acquisition/Organic Acquisition/Content"
mk "$ROOT/Customer Acquisition/Organic Acquisition/Community"
mk "$ROOT/Customer Acquisition/Organic Acquisition/Social Media"
mk "$ROOT/Customer Acquisition/Organic Acquisition/Word of Mouth"
mk "$ROOT/Customer Acquisition/Attribution/Attribution Models"
mk "$ROOT/Customer Acquisition/Attribution/UTM Framework"
mk "$ROOT/Customer Acquisition/Attribution/Multi Touch Reports"
mk "$ROOT/Customer Acquisition/Attribution/Channel Mix"
mk "$ROOT/Customer Acquisition/AI Workflows/Channel Optimizer"
mk "$ROOT/Customer Acquisition/AI Workflows/CAC Calculator"
mk "$ROOT/Customer Acquisition/AI Workflows/Attribution Advisor"

# Retention & Loyalty
mk "$ROOT/Retention & Loyalty/Onboarding/Onboarding Flows"
mk "$ROOT/Retention & Loyalty/Onboarding/Welcome Sequences"
mk "$ROOT/Retention & Loyalty/Onboarding/Activation Checklist"
mk "$ROOT/Retention & Loyalty/Onboarding/Aha Moment Design"
mk "$ROOT/Retention & Loyalty/Onboarding/Time to Value"
mk "$ROOT/Retention & Loyalty/Customer Success/Success Plans"
mk "$ROOT/Retention & Loyalty/Customer Success/QBR Templates"
mk "$ROOT/Retention & Loyalty/Customer Success/Health Scores"
mk "$ROOT/Retention & Loyalty/Customer Success/At Risk Customers"
mk "$ROOT/Retention & Loyalty/Customer Success/Expansion Plays"
mk "$ROOT/Retention & Loyalty/Loyalty Programs/Points Systems"
mk "$ROOT/Retention & Loyalty/Loyalty Programs/Tier Programs"
mk "$ROOT/Retention & Loyalty/Loyalty Programs/VIP Programs"
mk "$ROOT/Retention & Loyalty/Loyalty Programs/Rewards Catalog"
mk "$ROOT/Retention & Loyalty/Loyalty Programs/Program Analytics"
mk "$ROOT/Retention & Loyalty/Churn Prevention/Churn Signals"
mk "$ROOT/Retention & Loyalty/Churn Prevention/Intervention Playbooks"
mk "$ROOT/Retention & Loyalty/Churn Prevention/Save Offers"
mk "$ROOT/Retention & Loyalty/Churn Prevention/Cancellation Flows"
mk "$ROOT/Retention & Loyalty/Churn Prevention/Win Back Campaigns"
mk "$ROOT/Retention & Loyalty/Community/Community Strategy"
mk "$ROOT/Retention & Loyalty/Community/Forum Management"
mk "$ROOT/Retention & Loyalty/Community/User Groups"
mk "$ROOT/Retention & Loyalty/Community/Ambassador Program"
mk "$ROOT/Retention & Loyalty/Community/Community Events"
mk "$ROOT/Retention & Loyalty/AI Workflows/Churn Predictor"
mk "$ROOT/Retention & Loyalty/AI Workflows/Loyalty Designer"
mk "$ROOT/Retention & Loyalty/AI Workflows/CS Playbook Builder"

# Content Engine
mk "$ROOT/Content Engine/Content Strategy/Pillar Topics"
mk "$ROOT/Content Engine/Content Strategy/Topic Clusters"
mk "$ROOT/Content Engine/Content Strategy/Content Pillars"
mk "$ROOT/Content Engine/Content Strategy/Audience Journey Map"
mk "$ROOT/Content Engine/Content Strategy/Competitive Content"
mk "$ROOT/Content Engine/Content Production/Blog Posts"
mk "$ROOT/Content Engine/Content Production/Case Studies"
mk "$ROOT/Content Engine/Content Production/Whitepapers"
mk "$ROOT/Content Engine/Content Production/Infographics"
mk "$ROOT/Content Engine/Content Production/Video Scripts"
mk "$ROOT/Content Engine/Content Production/Podcast Scripts"
mk "$ROOT/Content Engine/Content Distribution/Publish Calendar"
mk "$ROOT/Content Engine/Content Distribution/Repurposing Plan"
mk "$ROOT/Content Engine/Content Distribution/Syndication"
mk "$ROOT/Content Engine/Content Distribution/Amplification"
mk "$ROOT/Content Engine/Copywriting/Sales Copy"
mk "$ROOT/Content Engine/Copywriting/Ad Copy"
mk "$ROOT/Content Engine/Copywriting/Email Copy"
mk "$ROOT/Content Engine/Copywriting/Landing Page Copy"
mk "$ROOT/Content Engine/Copywriting/Social Copy"
mk "$ROOT/Content Engine/Copywriting/Copy Swipe File"
mk "$ROOT/Content Engine/Content Analytics/Traffic Reports"
mk "$ROOT/Content Engine/Content Analytics/Engagement Metrics"
mk "$ROOT/Content Engine/Content Analytics/Lead Attribution"
mk "$ROOT/Content Engine/Content Analytics/Top Performers"
mk "$ROOT/Content Engine/Brand Assets/Logo Files"
mk "$ROOT/Content Engine/Brand Assets/Color Palette"
mk "$ROOT/Content Engine/Brand Assets/Typography"
mk "$ROOT/Content Engine/Brand Assets/Templates"
mk "$ROOT/Content Engine/Brand Assets/Style Guide"
mk "$ROOT/Content Engine/AI Workflows/Content Brief Generator"
mk "$ROOT/Content Engine/AI Workflows/Content Repurposer"
mk "$ROOT/Content Engine/AI Workflows/SEO Content Writer"

# Outreach & Campaigns
mk "$ROOT/Outreach & Campaigns/Email Campaigns/Cold Outreach"
mk "$ROOT/Outreach & Campaigns/Email Campaigns/Nurture Campaigns"
mk "$ROOT/Outreach & Campaigns/Email Campaigns/Launch Campaigns"
mk "$ROOT/Outreach & Campaigns/Email Campaigns/Re Engagement"
mk "$ROOT/Outreach & Campaigns/Email Campaigns/Promotional"
mk "$ROOT/Outreach & Campaigns/Email Campaigns/Transactional"
mk "$ROOT/Outreach & Campaigns/LinkedIn Campaigns/Connection Sequences"
mk "$ROOT/Outreach & Campaigns/LinkedIn Campaigns/InMail Templates"
mk "$ROOT/Outreach & Campaigns/LinkedIn Campaigns/Content Campaigns"
mk "$ROOT/Outreach & Campaigns/LinkedIn Campaigns/Event Promotion"
mk "$ROOT/Outreach & Campaigns/LinkedIn Campaigns/Thought Leadership"
mk "$ROOT/Outreach & Campaigns/Cold Email/Prospect Lists"
mk "$ROOT/Outreach & Campaigns/Cold Email/Email Sequences"
mk "$ROOT/Outreach & Campaigns/Cold Email/Personalization Snippets"
mk "$ROOT/Outreach & Campaigns/Cold Email/Subject Line Tests"
mk "$ROOT/Outreach & Campaigns/Cold Email/Reply Templates"
mk "$ROOT/Outreach & Campaigns/Cold Email/Campaign Results"
mk "$ROOT/Outreach & Campaigns/Multi Channel/Email + LinkedIn"
mk "$ROOT/Outreach & Campaigns/Multi Channel/Email + Call"
mk "$ROOT/Outreach & Campaigns/Multi Channel/Social + Email"
mk "$ROOT/Outreach & Campaigns/Multi Channel/ABM Plays"
mk "$ROOT/Outreach & Campaigns/Campaign Analytics/Open Rates"
mk "$ROOT/Outreach & Campaigns/Campaign Analytics/Reply Rates"
mk "$ROOT/Outreach & Campaigns/Campaign Analytics/Meeting Booked Rates"
mk "$ROOT/Outreach & Campaigns/Campaign Analytics/Campaign ROI"
mk "$ROOT/Outreach & Campaigns/Campaign Analytics/A-B Test Results"
mk "$ROOT/Outreach & Campaigns/AI Workflows/Sequence Writer"
mk "$ROOT/Outreach & Campaigns/AI Workflows/Subject Line Tester"
mk "$ROOT/Outreach & Campaigns/AI Workflows/Reply Handler"

# Analytics & Reporting
mk "$ROOT/Analytics & Reporting/Growth Metrics/MRR ARR"
mk "$ROOT/Analytics & Reporting/Growth Metrics/Revenue Growth Rate"
mk "$ROOT/Analytics & Reporting/Growth Metrics/Customer Count"
mk "$ROOT/Analytics & Reporting/Growth Metrics/NRR GRR"
mk "$ROOT/Analytics & Reporting/Growth Metrics/Growth Accounting"
mk "$ROOT/Analytics & Reporting/Acquisition Metrics/Traffic Sources"
mk "$ROOT/Analytics & Reporting/Acquisition Metrics/Lead Volume"
mk "$ROOT/Analytics & Reporting/Acquisition Metrics/CAC Tracking"
mk "$ROOT/Analytics & Reporting/Acquisition Metrics/Conversion Rates"
mk "$ROOT/Analytics & Reporting/Acquisition Metrics/Pipeline Value"
mk "$ROOT/Analytics & Reporting/Engagement Metrics/DAU WAU MAU"
mk "$ROOT/Analytics & Reporting/Engagement Metrics/Session Metrics"
mk "$ROOT/Analytics & Reporting/Engagement Metrics/Feature Usage"
mk "$ROOT/Analytics & Reporting/Engagement Metrics/NPS CSAT"
mk "$ROOT/Analytics & Reporting/Revenue Metrics/ARPU ARPA"
mk "$ROOT/Analytics & Reporting/Revenue Metrics/LTV Tracking"
mk "$ROOT/Analytics & Reporting/Revenue Metrics/Expansion Revenue"
mk "$ROOT/Analytics & Reporting/Revenue Metrics/Churn Revenue"
mk "$ROOT/Analytics & Reporting/Dashboards/Growth Dashboard"
mk "$ROOT/Analytics & Reporting/Dashboards/Marketing Dashboard"
mk "$ROOT/Analytics & Reporting/Dashboards/Sales Dashboard"
mk "$ROOT/Analytics & Reporting/Dashboards/BD Dashboard"
mk "$ROOT/Analytics & Reporting/Dashboards/Executive Dashboard"
mk "$ROOT/Analytics & Reporting/Reports/Weekly Growth Reports"
mk "$ROOT/Analytics & Reporting/Reports/Monthly Reviews"
mk "$ROOT/Analytics & Reporting/Reports/Quarterly Business Reviews"
mk "$ROOT/Analytics & Reporting/Reports/Investor Updates"
mk "$ROOT/Analytics & Reporting/AI Workflows/Metrics Analyzer"
mk "$ROOT/Analytics & Reporting/AI Workflows/Report Generator"
mk "$ROOT/Analytics & Reporting/AI Workflows/Growth Diagnoser"

# Archive
mk "$ROOT/Archive/Past Campaigns"
mk "$ROOT/Archive/Old Experiments"
mk "$ROOT/Archive/Closed Deals"
mk "$ROOT/Archive/Old Strategies"
mk "$ROOT/Archive/Deprecated Playbooks"

echo "--------------------------------------------------"
echo "✅ Done! $COUNT folders created."
echo "📂 Open: $(pwd)/$ROOT"
echo ""
